services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - 127.0.0.1:5000:5000
    env_file:
      - .env
    networks:
      - default
      - vault-network
    restart: always

  redis:
    image: mirror.gcr.io/redis:7.4
    restart: always
    volumes:
      - redisdata:/data

networks:
  vault-network:
    external: true

volumes:
  redisdata: