services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - 127.0.0.1:5000:5000
    env_file:
      - .env
    networks:
      - default
      - vault-network
    restart: always

networks:
  vault-network:
    external: true