services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 127.0.0.1:5000:5000
    env_file:
      - .env
    restart: always
    networks:
      - default
      - vault-network

networks:
  vault-network:
    external: true