name: Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        rsync -avz --exclude='.git' --exclude='.github' -e "ssh -o StrictHostKeyChecking=no" . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/frontend/

    - name: Create .env
      run: |
        cat << EOF > .env
        # App configuration
        BACKEND_URL=${{ secrets.BACKEND_URL }}
        BACKEND_USERNAME=${{ secrets.BACKEND_USERNAME }}
        BACKEND_PASSWORD=${{ secrets.BACKEND_PASSWORD }}

        SECRET_KEY=${{ secrets.COOKIES_SECRET_KEY}}
        EOF

    - name: Run docker compose on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/${{ secrets.SERVER_USER }}/frontend
          source .env
          sudo docker compose -f compose.prod.yaml down
          sudo docker compose -f compose.prod.yaml pull
          sudo docker compose -f compose.prod.yaml up -d --build
        EOF